### ISSUE TITLE
Release our own LLVM build

### ISSUE THREAD

**Issue by xermicus** [paritytech/revive#86]
```[tasklist]
### Tasks
- [x] 1. Fork and port the era compiler LLVM builder
- [x] 2. Change revive to use those builds. The entire utils directory should be obselete.
- [x] 3. Remove the vendored compiler-rt and use the one from the revive-llvm CI.
- [ ] 4. Create a test workflow for the revive-llvm builder for Linux, MacOS and Windows
- [x] 5. ~~Create a release workflow for the revive-llvm tool itself.~~
- [ ] 6. Create a release workflow for LLVM.
```

Considerations regarding step 6.:
- The tarball for each architecture should contain the `target-final` directory only.
- `emscripten` and `musl` builds are cross compilation artifacts. The build host architecture shouldn't matter (though it should probably be built on a ubuntu host anyways).

**Comment by xermicus** [comment]
Update: I am working on the llvm-builder. I have it in a working state and am currently integrating it as a crate into this repository.

This will fully unblock the release worflows.

**Comment by xermicus** [comment]
As discussed with @mutantcornholio. LLVM build artifacts will be released together with the [binaries](#93 ).
