### ISSUE TITLE
Detect problematic blob size at link time

### ISSUE THREAD

**Issue by xermicus** [paritytech/revive#96]
Emit a compiler warning (or error) if we detect the final blob size to exceed the pallets [limits](https://github.com/paritytech/polkadot-sdk/blob/master/substrate/frame/revive/src/limits.rs).

### Tasks
- [ ] Add a command line flag to provide the memory limit (different chains can exhibit different limits), and assume AH as default
- [ ] Helper to calculate the maximum linked blob size given the static memory buffer and the the pallet limits
- [ ] Check it after linting and emit a warning if over the threshold
- [ ] By default it should error out but we want to have a flag to ignore it

**Comment by dimartiro** [comment]
Addressing this in #599
